name: Natan Weinberger
version: 1.0
markdown: kramdown

title: Natan Weinberger
description: A blog with helpful tidbits

kramdown:
  input: GFM
  syntax_highlighter: rouge

destination: web

prod_url: https://natanweinberger.github.io
baseurl: ''

github:
  user: https://github.com/natanweinberger
  repo: https://github.com/natanweinberger/natanweinberger.github.io
repository: natanweinberger/natanweinberger.github.io
